-- CareGuard AI - Oracle Database 26ai demo schema
-- SYNTHETIC DATA ONLY. Do not load real PHI/ePHI.

CREATE TABLE cg_patients (
    patient_id       VARCHAR2(40) PRIMARY KEY,
    synthetic_name   VARCHAR2(100) NOT NULL,
    synthetic_flag   CHAR(1) DEFAULT 'Y' CHECK (synthetic_flag = 'Y')
);

CREATE TABLE cg_encounters (
    encounter_id     VARCHAR2(40) PRIMARY KEY,
    patient_id       VARCHAR2(40) NOT NULL REFERENCES cg_patients(patient_id),
    encounter_type   VARCHAR2(100),
    status            VARCHAR2(40)
);

CREATE TABLE cg_care_tasks (
    task_id           VARCHAR2(40) PRIMARY KEY,
    patient_id        VARCHAR2(40) NOT NULL,
    encounter_id      VARCHAR2(40) NOT NULL,
    task_type         VARCHAR2(100),
    task_status       VARCHAR2(40),
    CONSTRAINT cg_task_patient_fk FOREIGN KEY(patient_id) REFERENCES cg_patients(patient_id),
    CONSTRAINT cg_task_enc_fk FOREIGN KEY(encounter_id) REFERENCES cg_encounters(encounter_id)
);

CREATE TABLE cg_document_chunks (
    chunk_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id            VARCHAR2(40) NOT NULL,
    title             VARCHAR2(200) NOT NULL,
    chunk_text        CLOB NOT NULL,
    classification    VARCHAR2(40) NOT NULL,
    allowed_role      VARCHAR2(60) NOT NULL,
    allowed_purpose   VARCHAR2(60) NOT NULL,
    patient_id        VARCHAR2(40),
    encounter_id      VARCHAR2(40),
    approval_status   VARCHAR2(20) DEFAULT 'APPROVED',
    effective_date    DATE DEFAULT SYSDATE,
    content_hash      VARCHAR2(128),
    embedding         VECTOR(384, FLOAT32)
);

CREATE TABLE cg_action_requests (
    request_id        VARCHAR2(64) PRIMARY KEY,
    action_type       VARCHAR2(100) NOT NULL,
    status            VARCHAR2(20) NOT NULL,
    created_by        VARCHAR2(100) NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE cg_ai_audit_log (
    event_id           VARCHAR2(64) PRIMARY KEY,
    event_time         TIMESTAMP DEFAULT SYSTIMESTAMP,
    user_id            VARCHAR2(100),
    role_name          VARCHAR2(60),
    purpose_of_use     VARCHAR2(60),
    patient_id         VARCHAR2(40),
    encounter_id       VARCHAR2(40),
    event_type         VARCHAR2(60),
    source_ids         VARCHAR2(1000),
    details_json       CLOB
);

CREATE TABLE cg_security_events (
    event_id           VARCHAR2(64) PRIMARY KEY,
    event_time         TIMESTAMP DEFAULT SYSTIMESTAMP,
    event_type         VARCHAR2(60),
    severity           VARCHAR2(20),
    details_json       CLOB
);
